# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

permissions: read-all
name: Build / test
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake_ubuntu_2404:
    name: Detect targets on ${{ matrix.name }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - name: Clang-18
            extra_deps: clang-18
            c_compiler: clang-18
            cxx_compiler: clang++-18
            # Disable AVX3_SPR/AVX3_ZEN4 targets in GitHub workflow build with
            # Clang 16 or later to work around crashes that occur with Clang 16
            # or later when some of the Google Highway tests are compiled with
            # all x86 targets enabled
            cxx_flags: -DHWY_DISABLED_TARGETS=0x50
            cxx_standard: 17

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit  # cannot be block - runner does git checkout

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.0.0

      - name: Install deps
        run: sudo apt-get install ${{ matrix.extra_deps }}

      - name: Build and detect targets
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=2
          export CTEST_PARALLEL_LEVEL=2
          CXXFLAGS="${{ matrix.cxx_flags }}" CC=${{ matrix.c_compiler }} CXX=${{ matrix.cxx_compiler }} cmake -G "Unix Makefiles" -DHWY_WARNINGS_ARE_ERRORS=ON -DHWY_TEST_STANDALONE=ON -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} ${{ matrix.extra_cmake_flags }} -B out .
          cmake --build out --target hwy_list_targets

  cmake_macos_13:
    name: Detect targets on macOS 13
    runs-on: macos-13

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.0.0

      - name: Build and detect targets
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=2
          export CTEST_PARALLEL_LEVEL=2
          CXXFLAGS="-msse4.2 -mpclmul -maes" cmake -G "Unix Makefiles" -DHWY_WARNINGS_ARE_ERRORS=ON -DCMAKE_CXX_STANDARD=17 -DHWY_ENABLE_CONTRIB=OFF -DHWY_TEST_STANDALONE=ON -B out .
          cmake --build out --target hwy_list_targets

  cmake_macos_14:
    name: Detect targets on macOS 14
    runs-on: macos-14

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.0.0

      - name: Build and detect targets
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=2
          export CTEST_PARALLEL_LEVEL=2
          cmake -G "Unix Makefiles" -DHWY_WARNINGS_ARE_ERRORS=ON -DCMAKE_CXX_STANDARD=17 -DHWY_ENABLE_CONTRIB=OFF -DHWY_TEST_STANDALONE=ON -DCMAKE_OSX_ARCHITECTURES=x86_64 -B out .
          cmake --build out --target hwy_list_targets
