# https://github.com/marketplace/actions/run-on-architecture
name: Foreign architectures

on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  multiarch:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu_latest
            cxx_flags: -Wno-psabi -DHWY_DISABLED_TARGETS=0x6000000000000000
          - arch: armv7
            distro: ubuntu_latest
            cxx_flags: -Wno-psabi
            cmake_flags: -DHWY_CMAKE_ARM7:BOOL=ON
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build and test
      uses: uraimo/run-on-arch-action@v2.8.1
      id: build
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
        # Not required, but speeds up builds
        githubToken: ${{ github.token }}
        install: |
          apt-get update -q -y
          apt-get install -q -y --no-install-recommends \
                build-essential \
                cmake \
                ninja-build \
                ;
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=2
          export CTEST_PARALLEL_LEVEL=2
          CXXFLAGS="${{ matrix.cxx_flags }}" cmake -GNinja ${{ matrix.cmake_flags }} -DHWY_TEST_STANDALONE=ON -DHWY_ENABLE_CONTRIB=OFF -DHWY_WARNINGS_ARE_ERRORS=ON -B out .
          cmake --build out --target hwy_list_targets
  cmake_macos_15:
    name: Build and test on macOS 15
    runs-on: macos-15

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.0.0

      - name: Build and test
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=2
          export CTEST_PARALLEL_LEVEL=2
          CXXFLAGS="-DHWY_DISABLED_TARGETS=0x6000000000000000 -DHWY_HAVE_RUNTIME_DISPATCH_APPLE=1" cmake -G "Unix Makefiles" -DHWY_TEST_STANDALONE=ON -DHWY_ENABLE_CONTRIB=OFF -DHWY_WARNINGS_ARE_ERRORS=ON -DCMAKE_CXX_STANDARD=17 -B out .
          cmake --build out --target hwy_list_targets
